[platformio]
default_envs = xiao_rp2040

[env:xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = seeed_xiao_rp2040
board_build.core = earlephilhower

board_build.filesystem_size = 0.5m  ;this is how the FATFS size is set onboard

monitor_speed = 115200

lib_deps = 
    zz-cat/CRSFforArduino@^2025.12.11
    khoih-prog/RP2040_PWM
    https://github.com/sparkfun/SparkFun_LIS331_Arduino_Library
    fastled/FastLED
    https://github.com/bastian2001/pico-bidir-dshot.git